
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WalletServiceEndpointService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/WS/WalletService?wsdl")
public class WalletServiceEndpointService
    extends Service
{

    private final static URL WALLETSERVICEENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WALLETSERVICEENDPOINTSERVICE_EXCEPTION;
    private final static QName WALLETSERVICEENDPOINTSERVICE_QNAME = new QName("http://service/", "WalletServiceEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/WalletService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WALLETSERVICEENDPOINTSERVICE_WSDL_LOCATION = url;
        WALLETSERVICEENDPOINTSERVICE_EXCEPTION = e;
    }

    public WalletServiceEndpointService() {
        super(__getWsdlLocation(), WALLETSERVICEENDPOINTSERVICE_QNAME);
    }

    public WalletServiceEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WALLETSERVICEENDPOINTSERVICE_QNAME, features);
    }

    public WalletServiceEndpointService(URL wsdlLocation) {
        super(wsdlLocation, WALLETSERVICEENDPOINTSERVICE_QNAME);
    }

    public WalletServiceEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WALLETSERVICEENDPOINTSERVICE_QNAME, features);
    }

    public WalletServiceEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WalletServiceEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WalletService
     */
    @WebEndpoint(name = "WalletServiceEndpointPort")
    public WalletService getWalletServiceEndpointPort() {
        return super.getPort(new QName("http://service/", "WalletServiceEndpointPort"), WalletService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WalletService
     */
    @WebEndpoint(name = "WalletServiceEndpointPort")
    public WalletService getWalletServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "WalletServiceEndpointPort"), WalletService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WALLETSERVICEENDPOINTSERVICE_EXCEPTION!= null) {
            throw WALLETSERVICEENDPOINTSERVICE_EXCEPTION;
        }
        return WALLETSERVICEENDPOINTSERVICE_WSDL_LOCATION;
    }

}
