
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WalletService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WalletService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod(operationName = "UpdatePlayerBalance")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdatePlayerBalance", targetNamespace = "http://service/", className = "service.UpdatePlayerBalance")
    @ResponseWrapper(localName = "UpdatePlayerBalanceResponse", targetNamespace = "http://service/", className = "service.UpdatePlayerBalanceResponse")
    @Action(input = "http://service/WalletService/UpdatePlayerBalanceRequest", output = "http://service/WalletService/UpdatePlayerBalanceResponse")
    public List<Object> updatePlayerBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
